apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-auth
  namespace: database
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-platform
  target:
    name: postgresql-auth
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: database/postgresql
        property: postgres-password
    - secretKey: password
      remoteRef:
        key: database/postgresql
        property: app-password
