apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: apisix
  namespace: platform
spec:
  interval: 10m0s
  chart:
    spec:
      chart: apisix
      version: ">=2.7.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: apisix
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    etcd:
      enabled: false
    ingress-controller:
      enabled: false
    dashboard:
      enabled: false
    gateway:
      type: ClusterIP
    apisix:
      deployment:
        role: traditional
        roleTraditional:
          configProvider: yaml
      standalone:
        enabled: true
      admin:
        enabled: false

