apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apisix-gateway
  namespace: platform
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.svc.plus,api-pre.svc.plus
spec:
  ingressClassName: caddy
  tls:
    - hosts:
        - api.svc.plus
        - api-pre.svc.plus
      secretName: apisix-gateway-tls
  rules:
    - host: api.svc.plus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apisix-gateway
                port:
                  number: 80
    - host: api-pre.svc.plus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apisix-gateway
                port:
                  number: 80

