apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k3s-platform-chart
  namespace: platform
spec:
  interval: 10m0s
  url: oci://ghcr.io/x-evor/k3s-platform-chart
  ref:
    semver: "0.1.1"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
