apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: accounts-chart
spec:
  interval: 10m0s
  url: oci://ghcr.io/x-evor/app-service
  ref:
    semver: "0.1.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
