apiVersion: v1
kind: Service
metadata:
  name: postgresql-tls-placeholder
  namespace: platform
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: postgresql-tls-placeholder
