apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-stunnel-client
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: stunnel-client
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/name: postgresql
  template:
    metadata:
      labels:
        app: postgresql-stunnel-client
        app.kubernetes.io/component: stunnel-client
        app.kubernetes.io/instance: postgresql
        app.kubernetes.io/name: postgresql
    spec:
      imagePullSecrets:
        - name: postgresql-ghcr-pull
      containers:
        - name: stunnel-client
          image: ghcr.io/x-evor/postgresql.svc.plus/stunnel-client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 15432
          volumeMounts:
            - name: stunnel-config
              mountPath: /etc/stunnel/stunnel.conf
              subPath: stunnel.conf
      volumes:
        - name: stunnel-config
          configMap:
            name: postgresql-stunnel-client
