apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-stunnel-client
  namespace: database
data:
  stunnel.conf: |
    foreground = yes
    debug = 5
    [postgres-client]
    client = yes
    accept = 0.0.0.0:15432
    connect = postgresql-stunnel-server.database.svc.cluster.local:5433
    verifyChain = no
    sslVersionMin = TLSv1.2
    options = NO_SSLv2
    options = NO_SSLv3
    TIMEOUTclose = 0
