apiVersion: v1
kind: Service
metadata:
  name: postgresql-stunnel-client
  namespace: database
spec:
  selector:
    app: postgresql-stunnel-client
  ports:
    - name: postgres
      port: 15432
      targetPort: 15432
