service:
  replicaCount: 1
  global:
    imagePullPolicy: Always
    tag: latest
    env:
      APP_ENV: pre
      ACCOUNTS_BASE_URL: https://accounts-pre.svc.plus
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 384Mi
  pdb:
    minAvailable: 1
