replicaCount: 2
image:
  repository: ghcr.io/x-evor/accounts
  tag: release
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 768Mi
pdb:
  minAvailable: 1
env:
  APP_ENV: production
  DB_SCHEMA: core_prod
