apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cert-manager-kustomization.yaml
  - postgresql-tls-platform-kustomization.yaml
  - postgresql-tls-database-kustomization.yaml
  - postgresql-prod-kustomization.yaml
  - stunnel-server-kustomization.yaml
  - stunnel-client-prod-kustomization.yaml
  - console-prod-kustomization.yaml
  - accounts-prod-kustomization.yaml
  - observability-kustomization.yaml

# cert-manager owns postgresql-tls in each namespace; no cross-namespace sync job.
