apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - postgresql-tls-sync-kustomization.yaml
  - postgresql-prod-kustomization.yaml
  - stunnel-server-kustomization.yaml
  - stunnel-client-prod-kustomization.yaml
  - console-prod-kustomization.yaml
  - accounts-prod-kustomization.yaml
  - observability-kustomization.yaml

# Sync marker for Flux reconciliation on postgresql-prod.svc.plus.
