---
- name: Ensure Cloudflare DNS Record
  cloudflare_dns_record:
    state: present
    zone: "{{ cloudflare_dns_domain }}"
    rr: "{{ cloudflare_dns_rr }}"
    type: "{{ cloudflare_dns_type }}"
    value: "{{ cloudflare_dns_value }}"
    ttl: "{{ cloudflare_dns_ttl }}"
    proxied: "{{ cloudflare_dns_proxied }}"
    priority: "{{ cloudflare_dns_priority }}"
    api_token: "{{ cloudflare_api_token }}"
  register: dns_result

- debug:
    var: dns_result

