apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: console-env
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-platform
  target:
    name: console-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: core/prod/console

