apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - platform-kustomization.yaml
  - database-kustomization.yaml
  - observability-kustomization.yaml
  - console-prod-kustomization.yaml
  - accounts-prod-kustomization.yaml
  - pre-kustomization.yaml

# Sync marker for Flux reconciliation on jp-k3s-vultr.svc.plus.
