apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-secrets-stack
  namespace: flux-system
spec:
  interval: 5m0s
  prune: true
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: platform-config
  path: ./infra/platform-secrets
  dependsOn:
    - name: platform-stack
