apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-stunnel-server
  namespace: database
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-platform
  target:
    name: postgresql-stunnel-server
    creationPolicy: Owner
  data:
    - secretKey: server-cert.pem
      remoteRef:
        key: database/postgresql-stunnel
        property: server-cert.pem
    - secretKey: server-key.pem
      remoteRef:
        key: database/postgresql-stunnel
        property: server-key.pem
