apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-stunnel-client
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: stunnel-client
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/name: postgresql
  template:
    metadata:
      labels:
        app: postgresql-stunnel-client
        app.kubernetes.io/component: stunnel-client
        app.kubernetes.io/instance: postgresql
        app.kubernetes.io/name: postgresql
    spec:
      imagePullSecrets:
        - name: postgresql-ghcr-pull
      containers:
        - name: stunnel-client
          image: ghcr.io/x-evor/postgresql.svc.plus/stunnel-client:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STUNNEL_SERVICE
              value: postgres-client
            - name: STUNNEL_ACCEPT
              value: "15432"
            - name: STUNNEL_CONNECT
              value: postgresql-stunnel-server.database.svc.cluster.local:5433
            - name: STUNNEL_CRONTAB
              value: ""
          ports:
            - containerPort: 15432
