apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql-chart
  namespace: database
spec:
  interval: 5m0s
  url: oci://ghcr.io/svc-design/postgresql
  ref:
    semver: "1.1.0"
  secretRef:
    name: postgresql-ghcr-pull
